import { test, expect, type Page } from '@playwright/test';
async function login(page: Page) {
  await page.goto('/'); await page.getByLabel('密码', { exact: true }).fill('test-only-workbench-password');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.getByRole('heading', { name: '内容工作区' })).toBeVisible();
  await expect(page.locator('#article-form').getByLabel('标题', { exact: true })).not.toHaveValue('');
}
const saved = (page: Page) => expect(page.locator('#message')).toHaveText('已保存到私有工作区，未发布。');
const view = (page: Page, name: 'articles' | 'directory' | 'preview') => page.locator('#view-' + name).click();
const settings = (page: Page) => page.locator('#article-settings > summary').click();
async function createDraft(page: Page, title: string) {
  await page.getByRole('button', { name: '新建草稿', exact: true }).click();
  await page.locator('#article-form').getByLabel('标题', { exact: true }).fill(title);
  await page.locator('#article-form').getByLabel('Markdown 正文').fill('# 私有正文\n\n**可读预览**\n\n<script>window.attack = true</script>');
  const id = await page.locator('#article-form').getByLabel('稳定 ID').inputValue();
  await page.getByRole('button', { name: '保存文章', exact: true }).click(); await saved(page);
  return id;
}
test('writing, binding and map preview form a safe round trip without manually entering IDs', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await login(page);
  await expect(page.locator('#directory-view')).toBeHidden();
  const id = await createDraft(page, '浏览器测试草稿');
  expect(id).toMatch(/^note-[a-f0-9-]+$/);
  const article = page.locator('#article-form');
  await expect(article.getByLabel('稳定 ID')).toHaveAttribute('readonly', '');
  await expect(article.getByLabel('草稿（不公开）')).toBeChecked();
  await page.getByRole('button', { name: '预览当前正文', exact: true }).click();
  await expect(page.locator('#rendered-body h1')).toHaveText('私有正文');
  await expect(article.getByLabel('Markdown 正文')).toBeHidden();
  expect(await page.evaluate(() => 'attack' in window)).toBe(false);
  await page.getByRole('button', { name: '编辑正文', exact: true }).click();
  await expect(article.getByLabel('Markdown 正文')).toBeVisible();
  await view(page, 'directory');
  await expect(page.locator('#tree [data-node-id="compilers"]')).toBeVisible();
  await page.locator('#tree [data-node-id="software"]').click();
  await page.locator('#bind-panel > summary').click();
  const binding = page.locator('#bind-form'); await binding.getByRole('combobox', { name: '文章', exact: true }).selectOption(id);
  const nodeId = await binding.getByLabel('入口节点 ID').inputValue();
  await binding.getByRole('button', { name: '绑定到所选目录' }).click(); await saved(page);
  const publicResponse = page.waitForResponse(response => response.url().endsWith('/api/preview') && response.request().method() === 'POST');
  await view(page, 'preview');
  await expect(page.locator('#preview-caption')).toContainText('模拟公开地图');
  expect(JSON.stringify(await (await publicResponse).json())).not.toContain(nodeId);
  await page.getByRole('button', { name: '完整目录（含草稿）' }).click();
  await page.locator('#map-preview [data-id="software"]').click(); await page.locator(`#map-preview [data-id="${nodeId}"]`).click();
  await expect(page.locator('#map-preview .context-panel')).toContainText('浏览器测试草稿');
  await page.locator('#map-preview').getByRole('link', { name: '打开内容 →' }).click();
  await expect(page).toHaveURL(new URL('/', String(info.project.use.baseURL)).href);
  await expect(article.getByLabel('稳定 ID')).toHaveValue(id);
  await expect(page.locator('#view-articles')).toHaveAttribute('aria-pressed', 'true');
  await page.locator('#article-danger > summary').click();
  await page.getByRole('button', { name: '删除文章', exact: true }).click(); await expect(page.locator('#message')).toContainText('请先移除或重新绑定');
  await article.getByLabel('标题', { exact: true }).fill('改名后的文章'); await settings(page);
  await article.getByLabel('草稿（不公开）').uncheck();
  await article.getByLabel('Software', { exact: true }).check();
  await page.getByRole('button', { name: '保存文章', exact: true }).click(); await saved(page);
  await view(page, 'preview'); await page.getByRole('button', { name: '模拟公开地图' }).click();
  await page.locator('#map-preview [data-id="software"]').click(); await page.locator(`#map-preview [data-id="${nodeId}"]`).click();
  await expect(page.locator('#map-preview .context-panel')).toContainText('改名后的文章');
  await expect(page.locator('#map-preview .node.current .title')).toHaveCSS('fill', 'rgb(227, 228, 229)');
  await expect(page.locator('#map-preview').getByRole('link', { name: '打开内容 →' })).toHaveAttribute('href', '/notes/' + id + '/');
  await page.screenshot({ path: info.outputPath('workbench-map-preview.png'), fullPage: true });
  await page.reload(); await page.locator(`#articles [data-article-id="${id}"]`).click();
  await expect(article.getByLabel('标题', { exact: true })).toHaveValue('改名后的文章');
  await settings(page); await expect(article.getByLabel('Software', { exact: true })).toBeChecked(); await settings(page);
  await page.screenshot({ path: info.outputPath('workbench-editor.png'), fullPage: true });
  expect(errors).toEqual([]);
});
test('directory actions, collapsed branches and stale-version protection work across task views', async ({ page, context }) => {
  await login(page); await view(page, 'directory');
  await expect(page.locator('#tree [data-node-id="gcc"]')).toBeHidden();
  await page.getByRole('button', { name: '展开 Compilers', exact: true }).click();
  await expect(page.locator('#tree [data-node-id="gcc"]')).toBeVisible();
  await page.locator('#add-directory-panel > summary').click();
  const directory = page.locator('#add-directory-form');
  await directory.getByLabel('名称', { exact: true }).fill('新目录');
  const id = await directory.getByLabel('节点 ID', { exact: true }).inputValue();
  await directory.getByRole('button', { name: '添加到所选目录' }).click(); await saved(page);
  await expect(page.locator('#node-heading')).toHaveText('新目录');
  await page.locator('#directory-form').getByLabel('目录名称').fill('改名目录');
  await page.getByRole('button', { name: '保存目录', exact: true }).click(); await saved(page);
  await page.locator('#move-panel > summary').click();
  await page.locator('#move-form').getByLabel('目标父目录').selectOption('software');
  await page.locator('#move-form').getByRole('button', { name: '移动所选节点' }).click(); await saved(page);
  await expect(page.locator(`#tree [data-node-id="${id}"]`)).toBeVisible();
  await expect(page.locator('#node-breadcrumb')).toContainText('Software');
  const second = await context.newPage(); await second.goto('/');
  await expect(second.locator('#articles [data-article-id="hello"]')).toBeVisible();
  await view(page, 'articles'); await page.locator('#articles [data-article-id="hello"]').click();
  await page.locator('#article-form').getByLabel('标题', { exact: true }).fill('另一个页面保存的标题 ' + id);
  await page.getByRole('button', { name: '保存文章', exact: true }).click(); await saved(page);
  await second.locator('#articles [data-article-id="hello"]').click();
  await second.locator('#article-form').getByLabel('标题', { exact: true }).fill('不应该覆盖的旧版本');
  await second.getByRole('button', { name: '保存文章', exact: true }).click();
  await expect(second.locator('#message')).toContainText('另一个页面中保存');
  await expect(second.locator('#article-form').getByLabel('标题', { exact: true })).toHaveValue('不应该覆盖的旧版本');
  second.once('dialog', dialog => dialog.dismiss()); await view(second, 'directory');
  await expect(second.locator('#view-articles')).toHaveAttribute('aria-pressed', 'true');
  await expect(second.locator('#article-form').getByLabel('标题', { exact: true })).toHaveValue('不应该覆盖的旧版本'); await second.close();
  await view(page, 'directory'); await page.locator('#move-panel > summary').click();
  page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', { name: '移除所选节点及子树' }).click(); await saved(page);
  await expect(page.locator(`#tree [data-node-id="${id}"]`)).toHaveCount(0);
});
test('search, filters, keyboard save and advanced defaults preserve user edits', async ({ page }) => {
  await login(page); await page.getByRole('button', { name: '新建草稿', exact: true }).click();
  const article = page.locator('#article-form');
  await article.getByLabel('标题', { exact: true }).fill('Keyboard Note');
  const id = await article.getByLabel('稳定 ID').inputValue();
  expect(id).toMatch(/^keyboard-note(?:-\d+)?$/);
  await expect(article.getByLabel('文件路径')).toHaveValue('articles/' + id + '.md');
  await article.getByLabel('Markdown 正文').fill('不应丢失的正文');
  await expect(page.locator('#save-status')).toContainText('未保存');
  await expect(page.locator('#word-count')).toContainText('未保存');
  await page.getByLabel('搜索文章', { exact: true }).fill('不存在的关键词');
  await expect(page.locator('#article-list-empty')).toBeVisible();
  await expect(article.getByLabel('Markdown 正文')).toHaveValue('不应丢失的正文');
  await page.getByLabel('搜索文章', { exact: true }).fill('');
  await article.getByLabel('Markdown 正文').press('Control+s'); await saved(page);
  await expect(page.locator('#save-status')).toHaveText('已保存 · 仅私有');
  await page.getByLabel('筛选', { exact: true }).selectOption('draft');
  await expect(page.locator(`#articles [data-article-id="${id}"]`)).toBeVisible();
  await expect(page.locator('#articles [data-article-id="hello"]')).toHaveCount(0);
  await page.getByLabel('筛选', { exact: true }).selectOption('all');
  const savedBody = await article.getByLabel('Markdown 正文').inputValue();
  await settings(page); await page.locator('#article-settings .advanced > summary').click();
  await article.getByLabel('文件路径').fill('../unsafe.md');
  await page.getByRole('button', { name: '保存文章', exact: true }).click();
  await expect(page.locator('#message')).toHaveClass(/error/);
  await expect(article.getByLabel('文件路径')).toHaveValue('../unsafe.md');
  await expect(article.getByLabel('Markdown 正文')).toHaveValue(savedBody);
  await article.getByLabel('文件路径').fill('articles/' + id + '.md');
  await page.getByRole('button', { name: '保存文章', exact: true }).click(); await saved(page);
  await page.locator('#article-danger > summary').click();
  page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', { name: '删除文章', exact: true }).click(); await saved(page);
  await expect(page.locator(`#articles [data-article-id="${id}"]`)).toHaveCount(0);
});
test('responsive task views, map return and logout keep private data protected', async ({ page }, info) => {
  await login(page);
  for (const width of [1486, 768, 390]) {
    await page.setViewportSize({ width, height: 1000 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: info.outputPath(`workbench-${width}.png`), fullPage: true });
  }
  await expect(page.locator('#article-library')).toBeHidden();
  await page.getByRole('button', { name: /文章列表/ }).click();
  await expect(page.getByLabel('搜索文章', { exact: true })).toBeVisible();
  await page.locator('#articles [data-article-id="hello"]').click();
  await expect(page.locator('#article-library')).toBeHidden();
  await view(page, 'directory');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('workbench-directory-mobile.png'), fullPage: true });
  await view(page, 'preview');
  await page.locator('#map-preview [data-id="infrastructure"]').click();
  await page.locator('#map-preview [data-id="cicd"]').click();
  await page.locator('#map-preview [data-id="hello"]').click();
  const bounds = await page.locator('#map-preview .context-panel').boundingBox();
  expect(bounds!.x).toBeGreaterThanOrEqual(0); expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('#map-preview').getByRole('link', { name: '打开内容 →' }).click();
  await expect(page.locator('#article-form').getByLabel('稳定 ID')).toHaveValue('hello');
  await page.locator('.account-menu > summary').click();
  await page.getByRole('button', { name: '退出', exact: true }).click();
  await expect(page.getByRole('heading', { name: '登录工作台' })).toBeVisible();
  expect((await page.request.get('/api/workspace')).status()).toBe(401);
  expect((await page.request.get('/api/export')).status()).toBe(401);
});

test('connection failures, discarded switches and cross-form cancellation do not silently lose input', async ({ page }) => {
  await login(page);
  const article = page.locator('#article-form');
  await article.getByLabel('Markdown 正文').fill('断线时也要保留这段文字');
  await page.route('**/api/command', route => route.abort('failed'));
  await page.getByRole('button', { name: '保存文章', exact: true }).click();
  await expect(page.locator('#message')).toContainText('无法连接工作台');
  await expect(article.getByLabel('Markdown 正文')).toHaveValue('断线时也要保留这段文字');
  await expect(page.locator('#save-status')).toContainText('未保存');
  page.once('dialog', dialog => dialog.dismiss()); await view(page, 'preview');
  await expect(page.locator('#articles-view')).toBeVisible();
  await page.unroute('**/api/command');
  await article.getByLabel('Markdown 正文').press('Control+s'); await saved(page);
  await expect(article.getByLabel('Markdown 正文')).toBeFocused();
  await view(page, 'directory');
  await page.locator('#directory-form').getByLabel('目录名称').fill('尚未保存的目录名称');
  await page.locator('#add-directory-panel > summary').click();
  await page.locator('#add-directory-form').getByLabel('名称', { exact: true }).fill('不应新增的子目录');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: '添加到所选目录' }).click();
  await expect(page.locator('#directory-form').getByLabel('目录名称')).toHaveValue('尚未保存的目录名称');
  await expect(page.locator('#add-directory-form').getByLabel('名称', { exact: true })).toHaveValue('不应新增的子目录');
  await expect(page.locator('#tree')).not.toContainText('不应新增的子目录');
  await expect(page.locator('#save-status')).toContainText('未保存');
});
