import { test, expect, type Page } from '@playwright/test';
async function login(page: Page) {
  await page.goto('/'); await page.getByLabel('密码', { exact: true }).fill('test-only-workbench-password');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.getByRole('heading', { name: '内容工作区' })).toBeVisible();
}
const saved = (page: Page) => expect(page.locator('#message')).toHaveText('已保存到私有工作区，未发布。');
test('private editing binds a new draft, previews safely, persists and never changes the public map until marked publishable', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await login(page); const id = 'browser-' + Date.now();
  await expect(page.locator('#tree [data-node-id="compilers"]')).toBeVisible();
  await page.getByRole('button', { name: '新建草稿', exact: true }).click();
  const article = page.locator('#article-form');
  await article.getByLabel('稳定 ID').fill(id); await article.getByLabel('标题', { exact: true }).fill('浏览器测试草稿');
  await article.getByLabel('摘要', { exact: true }).fill('不会出现在公开地图');
  await article.getByLabel('Markdown 正文').fill('# 私有正文\n\n**可读预览**\n\n<script>window.attack = true</script>');
  await expect(article.getByLabel('草稿（不公开）')).toBeChecked();
  await page.getByRole('button', { name: '保存文章', exact: true }).click(); await saved(page);
  await expect(article.getByLabel('稳定 ID')).toHaveAttribute('readonly', '');
  await page.getByRole('button', { name: '预览当前正文', exact: true }).click();
  await expect(page.locator('#rendered-body h1')).toHaveText('私有正文');
  expect(await page.evaluate(() => 'attack' in window)).toBe(false);
  await page.locator('#tree [data-node-id="software"]').click();
  const binding = page.locator('#bind-form'); await binding.getByRole('combobox', { name: '文章', exact: true }).selectOption(id);
  await binding.getByLabel('入口节点 ID').fill(id + '-node'); await binding.getByRole('button', { name: '绑定到所选目录' }).click(); await saved(page);
  const publicResponse = page.waitForResponse(response => response.url().endsWith('/api/preview') && response.request().method() === 'POST');
  await page.getByRole('button', { name: '模拟公开地图' }).click();
  await expect(page.locator('#preview-caption')).toContainText('模拟公开地图');
  expect(JSON.stringify(await (await publicResponse).json())).not.toContain(id + '-node');
  await page.getByRole('button', { name: '完整目录（含草稿）' }).click();
  await page.locator('#map-preview [data-id="software"]').click(); await page.locator(`#map-preview [data-id="${id}-node"]`).click();
  await expect(page.locator('#map-preview .context-panel')).toContainText('浏览器测试草稿');
  await page.locator('#map-preview').getByRole('link', { name: '打开内容 →' }).click();
  await expect(page).toHaveURL(new URL('/', String(info.project.use.baseURL)).href); await expect(article.getByLabel('稳定 ID')).toHaveValue(id);
  await page.getByRole('button', { name: '删除文章', exact: true }).click(); await expect(page.locator('#message')).toContainText('请先移除或重新绑定');
  await article.getByLabel('标题', { exact: true }).fill('改名后的文章'); await article.getByLabel('草稿（不公开）').uncheck();
  await page.getByRole('button', { name: '保存文章', exact: true }).click(); await saved(page);
  await page.getByRole('button', { name: '模拟公开地图' }).click();
  await page.locator('#map-preview [data-id="software"]').click(); await page.locator(`#map-preview [data-id="${id}-node"]`).click();
  await expect(page.locator('#map-preview .context-panel')).toContainText('改名后的文章');
  await expect(page.locator('#map-preview .node.current .title')).toHaveCSS('fill', 'rgb(227, 228, 229)');
  await expect(page.locator('#map-preview').getByRole('link', { name: '打开内容 →' })).toHaveAttribute('href', '/notes/' + id + '/');
  await page.locator('.preview-section').screenshot({ path: info.outputPath('workbench-map-preview.png') });
  await page.reload(); await page.locator(`#articles [data-article-id="${id}"]`).click();
  await expect(article.getByLabel('标题', { exact: true })).toHaveValue('改名后的文章');
  await page.screenshot({ path: info.outputPath('workbench-editor.png'), fullPage: true });
  expect(errors).toEqual([]);
});
test('directory forms, conflict protection and unsaved-form guards work in the browser', async ({ page, context }) => {
  await login(page); const id = 'directory-' + Date.now();
  const directory = page.locator('#add-directory-form');
  await directory.getByLabel('节点 ID', { exact: true }).fill(id); await directory.getByLabel('名称', { exact: true }).fill('新目录');
  await directory.getByRole('button', { name: '添加到所选目录' }).click(); await saved(page);
  await page.locator(`#tree [data-node-id="${id}"]`).click();
  await page.locator('#directory-form').getByLabel('目录名称').fill('改名目录');
  await page.getByRole('button', { name: '保存目录', exact: true }).click(); await saved(page);
  await page.getByText('移动、排序与移除', { exact: true }).click();
  await page.locator('#move-form').getByLabel('目标父目录').selectOption('software');
  await page.locator('#move-form').getByRole('button', { name: '移动所选节点' }).click(); await saved(page);
  await expect(page.locator('#tree [data-node-id="software"]').locator('..').locator(`[data-node-id="${id}"]`)).toBeVisible();
  const second = await context.newPage(); await second.goto('/');
  await expect(second.locator('#articles [data-article-id="hello"]')).toBeVisible();
  await page.locator('#articles [data-article-id="hello"]').click();
  await page.locator('#article-form').getByLabel('标题', { exact: true }).fill('另一个页面保存的标题 ' + id);
  await page.getByRole('button', { name: '保存文章', exact: true }).click(); await saved(page);
  await second.locator('#articles [data-article-id="hello"]').click();
  await second.locator('#article-form').getByLabel('标题', { exact: true }).fill('不应该覆盖的旧版本');
  await second.getByRole('button', { name: '保存文章', exact: true }).click();
  await expect(second.locator('#message')).toContainText('另一个页面中保存');
  await expect(second.locator('#article-form').getByLabel('标题', { exact: true })).toHaveValue('不应该覆盖的旧版本');
  second.once('dialog', dialog => dialog.dismiss());
  await second.locator('#tree [data-node-id="software"]').click();
  await expect(second.locator('#article-form').getByLabel('标题', { exact: true })).toHaveValue('不应该覆盖的旧版本');
  await second.close();
  await page.locator(`#tree [data-node-id="${id}"]`).click();
  page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', { name: '移除所选节点及子树' }).click(); await saved(page);
  await expect(page.locator(`#tree [data-node-id="${id}"]`)).toHaveCount(0);
});
test('responsive workbench and logout keep private data behind authentication', async ({ page }, info) => {
  await login(page); await page.locator('#articles [data-article-id="hello"]').click();
  for (const width of [1486, 768, 390]) {
    await page.setViewportSize({ width, height: 1000 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: info.outputPath(`workbench-${width}.png`), fullPage: true });
  }
  await page.getByRole('button', { name: '模拟公开地图' }).click();
  await page.locator('#map-preview [data-id="infrastructure"]').click();
  await page.locator('#map-preview [data-id="cicd"]').click();
  await page.locator('#map-preview [data-id="hello"]').click();
  const bounds = await page.locator('#map-preview .context-panel').boundingBox();
  expect(bounds!.x).toBeGreaterThanOrEqual(0); expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390);
  await page.locator('#map-preview').getByRole('link', { name: '打开内容 →' }).click();
  await expect(page.locator('#article-form').getByLabel('稳定 ID')).toHaveValue('hello');
  await page.getByRole('button', { name: '退出', exact: true }).click();
  await expect(page.getByRole('heading', { name: '登录工作台' })).toBeVisible();
  expect((await page.request.get('/api/workspace')).status()).toBe(401);
  expect((await page.request.get('/api/export')).status()).toBe(401);
});
